version: '3.7'

services:
  spring-backend:
    build:
      context: ./courses-back
      dockerfile: ./docker/spring-boot.dockerfile
      args:
        - JAR_FILE=${JAR_FILE}
    image: courses/spring_backend:v1
    container_name: courses_spring
    ports:
      - ${DOCKER_SPRING_EXPOSED_PORT}:8001
    environment:
      jasypt.encryptor.password: ${SECRET_KEY}
    networks:
      - backend_net
      - frontend_net
    restart: on-failure
  
  mysqldb:
    build:
      context: ./courses-back
      dockerfile: ./docker/mysql.dockerfile
    image: courses/mysql:v1
    container_name: courses_mysql
    ports:
      - ${DOCKER_DB_EXPOSED_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      TZ: "Europe/Madrid"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend_net
    restart: on-failure

  mysqldb_test:
    build:
      context: ./courses-back
      dockerfile: ./docker/mysql-test.dockerfile
    image: courses/mysql_test:v1
    container_name: courses_mysql_test
    ports:
      - ${DOCKER_DB_EXPOSED_PORT_TEST}:3306
    volumes:
      - mysql_test:/var/lib/mysql
    environment:
      TZ: "Europe/Madrid"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DB_DATABASE_TEST}
      MYSQL_USER: ${DB_USERNAME_TEST}
      MYSQL_PASSWORD: ${DB_PASSWORD_TEST}
    networks:
      - backend_net
    restart: on-failure

  angular:
    build:
      context: ./courses-front
      dockerfile: ./docker/angular.dockerfile
    image: courses/angular:v1
    container_name: courses_angular
    ports:
      - ${ANGULAR_EXPOSED_PORT}:4200
      - ${KARMA_EXPOSED_PORT}:9876
    volumes:
      - './courses-front/:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend_net
    restart: on-failure

volumes:
  mysql:
  mysql_test:

networks:
  backend_net:
    name: backend_net
  frontend_net:
    name: frontend_net
