version: '3.7'

services:
  
  mysqldb:
    build:
      context: ./courses-back
      dockerfile: ./Dockerfile
    image: courses/mysql
    container_name: courses_mysql
    ports:
      - ${DOCKER_DB_EXPOSED_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      TZ: "Europe/Madrid"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - courses_net
    restart: on-failure

  angular:
    build:
      context: ./courses-front
      dockerfile: ./Dockerfile
    image: courses/angular
    container_name: courses_angular
    ports:
      - ${ANGULAR_EXPOSED_PORT}:4200
    volumes:
      - './courses-front/:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - courses_net
    restart: on-failure

volumes:
  mysql:

networks:
  courses_net:
    name: courses_net