version: '3.7'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: courses/angular
    container_name: courses_angular
    ports:
      - ${ANGULAR_EXPOSED_PORT}:4200
    volumes:
      - '.:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
