-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 16:01:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coursesdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coursesdb` ;

-- -----------------------------------------------------
-- Schema coursesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coursesdb`;

-- -----------------------------------------------------
-- Table `coursesdb`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coursesdb`.`teacher`;

CREATE TABLE IF NOT EXISTS `coursesdb`.`teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursesdb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coursesdb`.`course` ;

CREATE TABLE IF NOT EXISTS `coursesdb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `level` ENUM('Básico', 'Intermedio', 'Avanzado') NOT NULL,
  `hours` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `id_teacher` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  INDEX `fk_course_teacher_idx` (`id_teacher` ASC),
  CONSTRAINT `fk_course_teacher`
    FOREIGN KEY (`id_teacher`)
    REFERENCES `coursesdb`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `coursesdb`.`teacher` VALUES (1, 'Alejandra', 'Mateos', 30),
                                         (2, 'Roberto', 'Canales', 32),
                                         (3, 'David', 'Gómez', 29),
                                         (4, 'Alberto', 'Moratilla', 43),
                                         (5, 'Rubén', 'Aguilera', 30);
INSERT INTO `coursesdb`.`course` VALUES (1, 'Introducción a JSF 2', 'Intermedio', 25, 1, 2),
                                        (2, 'Novedades en Java 8', 'Básico', 10, 1, 3),
                                        (3, 'Java para sistemas', 'Básico', 25, 0, 4),
                                        (4, 'Angular 2', 'Intermedio', 25, 1, 5);
COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
